"""Static GLBA control template (backend mirror of ``frontend/src/data/glbaControls.ts``).

The DB stores only the editable owner/assessor responses, keyed by control id.
This module holds the reference data (titles, citations, objectives, test
procedures, required evidence, high-risk flags, scoring rules) so the backend
can render a self-contained assessment report without the frontend having to
ship the whole template up with every export request.

Keep this in sync with ``frontend/src/data/glbaControls.ts``.  ``glba_controls``
derives ``GLBA_CONTROL_IDS`` from this list so the two never drift on ordering.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import List


@dataclass(frozen=True)
class GlbaControl:
    id: str
    domain: str
    title: str
    high_risk: bool
    citation: str
    csf: str
    nist: str
    frequency: str
    objective: str
    procedure: str
    methods: List[str] = field(default_factory=list)
    evidence: List[str] = field(default_factory=list)
    scoring: str = ""


# Domain id -> human title (matches GLBA_DOMAINS on the frontend).
GLBA_DOMAINS: List[dict] = [
    {"id": "A", "title": "Program Governance & Board Oversight"},
    {"id": "B", "title": "Risk Assessment"},
    {"id": "C", "title": "Control of Risks (Safeguards)"},
    {"id": "D", "title": "Service Provider Oversight"},
    {"id": "E", "title": "Program Adjustment & Continuity"},
    {"id": "F", "title": "Privacy (Regulation P)"},
]

TEST_METHODS = ["Inquiry", "Observation", "Inspection", "Reperformance"]
RESULT_OPTIONS = ["Effective", "Deficient", "Not Implemented", "N/A"]


GLBA_CONTROLS: List[GlbaControl] = [
    GlbaControl(
        id="A-01",
        domain="A",
        title="Board-approved written Information Security Program",
        high_risk=False,
        citation="App B III.A",
        csf="CSF GV.OC",
        nist="800-53: PM-1",
        frequency="Annual",
        objective="A written ISP exists, is board-approved, and is current.",
        procedure="Inspect the ISP document; verify board or committee minutes show approval within the review cycle.",
        methods=["Inspection"],
        evidence=["ISP document", "Board/committee minutes"],
        scoring="Inspection required to rate Effective. Inquiry alone is insufficient.",
    ),
    GlbaControl(
        id="A-02",
        domain="A",
        title="Board oversight and delegation",
        high_risk=False,
        citation="App B III.A",
        csf="CSF GV.RR",
        nist="800-53: PM-2",
        frequency="Annual",
        objective="Board (or designated committee) oversees development, implementation, and maintenance of the ISP.",
        procedure="Inspect committee charter and delegation; confirm assigned accountability.",
        methods=["Inquiry", "Inspection"],
        evidence=["Committee charter", "Delegation memo"],
        scoring="Inspection required to rate Effective. Inquiry alone is insufficient.",
    ),
    GlbaControl(
        id="A-03",
        domain="A",
        title="Annual report to the board",
        high_risk=False,
        citation="App B III.F",
        csf="CSF GV.OV",
        nist="800-53: CA-2",
        frequency="Annual",
        objective="Management reports ISP status to the board at least annually, covering risk, test results, incidents, and recommendations.",
        procedure="Inspect the most recent report; verify content covers required elements.",
        methods=["Inspection"],
        evidence=["Annual ISP board report"],
        scoring="Inspection required to rate Effective. Inquiry alone is insufficient.",
    ),
    GlbaControl(
        id="A-04",
        domain="A",
        title="Designated program coordinator",
        high_risk=False,
        citation="App B III.A",
        csf="CSF GV.RR",
        nist="800-53: PM-2",
        frequency="Annual",
        objective="A qualified individual is designated to coordinate the ISP.",
        procedure="Inquire and inspect appointment record; confirm role authority.",
        methods=["Inquiry", "Inspection"],
        evidence=["Appointment record", "Job description"],
        scoring="Inspection required to rate Effective. Inquiry alone is insufficient.",
    ),
    GlbaControl(
        id="B-01",
        domain="B",
        title="Customer information risk assessment",
        high_risk=False,
        citation="App B III.B",
        csf="CSF ID.RA",
        nist="800-53: RA-3",
        frequency="Annual",
        objective="Reasonably foreseeable internal and external threats to customer information are identified.",
        procedure="Inspect the risk assessment; verify it covers threats to confidentiality, integrity, and availability of customer information.",
        methods=["Inspection"],
        evidence=["Risk assessment report"],
        scoring="Inspection required to rate Effective. Inquiry alone is insufficient.",
    ),
    GlbaControl(
        id="B-02",
        domain="B",
        title="Sensitivity and inventory of customer information",
        high_risk=False,
        citation="App B III.B.1",
        csf="CSF ID.AM",
        nist="800-53: RA-2, CM-8",
        frequency="Annual",
        objective="Customer information assets are identified and classified by sensitivity.",
        procedure="Inspect data inventory and classification; trace a sample of systems to the inventory.",
        methods=["Inspection", "Reperformance"],
        evidence=["Data inventory", "Classification policy"],
        scoring="Inspection required to rate Effective. Inquiry alone is insufficient.",
    ),
    GlbaControl(
        id="B-03",
        domain="B",
        title="Likelihood and impact analysis",
        high_risk=False,
        citation="App B III.B.2",
        csf="CSF ID.RA",
        nist="800-53: RA-3",
        frequency="Annual",
        objective="Risks are assessed for likelihood and potential damage.",
        procedure="Inspect scoring methodology; reperform scoring on a sample risk.",
        methods=["Inspection", "Reperformance"],
        evidence=["Risk scoring worksheet"],
        scoring="Inspection required to rate Effective. Inquiry alone is insufficient.",
    ),
    GlbaControl(
        id="B-04",
        domain="B",
        title="Sufficiency of existing controls",
        high_risk=False,
        citation="App B III.B.3",
        csf="CSF ID.RA",
        nist="800-53: CA-2",
        frequency="Annual",
        objective="Existing controls are evaluated against assessed risks.",
        procedure="Inspect gap analysis linking identified risks to mitigating controls.",
        methods=["Inspection"],
        evidence=["Control gap analysis"],
        scoring="Inspection required to rate Effective. Inquiry alone is insufficient.",
    ),
    GlbaControl(
        id="C-01",
        domain="C",
        title="Access controls",
        high_risk=True,
        citation="App B III.C.1.a",
        csf="CSF PR.AA",
        nist="800-53: AC-2, AC-3, AC-6",
        frequency="Quarterly",
        objective="Logical and physical access is restricted to authorized persons; least privilege enforced.",
        procedure="Inspect access control configuration; reperform access review on a sample of users; test least-privilege enforcement.",
        methods=["Inspection", "Reperformance"],
        evidence=["Access review", "RBAC configuration", "Sample user list"],
        scoring="high-risk control — Inspection + Reperformance required to rate Effective.",
    ),
    GlbaControl(
        id="C-02",
        domain="C",
        title="Physical access restrictions",
        high_risk=False,
        citation="App B III.C.1.b",
        csf="CSF PR.AA",
        nist="800-53: PE-2, PE-3",
        frequency="Semi-Annual",
        objective="Physical access to customer information is restricted at facilities.",
        procedure="Observe data center and facility controls; inspect badge logs.",
        methods=["Observation", "Inspection"],
        evidence=["Badge logs", "Facility walkthrough notes"],
        scoring="Inspection required to rate Effective. Inquiry alone is insufficient.",
    ),
    GlbaControl(
        id="C-03",
        domain="C",
        title="Encryption in transit and at rest",
        high_risk=True,
        citation="App B III.C.1.c",
        csf="CSF PR.DS",
        nist="800-53: SC-8, SC-28",
        frequency="Quarterly",
        objective="Customer information is encrypted in transit and at rest where appropriate.",
        procedure="Inspect encryption standards; reperform configuration checks on a sample of systems (TLS, disk/database encryption).",
        methods=["Inspection", "Reperformance"],
        evidence=["Cryptographic standard", "Configuration evidence", "Scan results"],
        scoring="high-risk control — Inspection + Reperformance required to rate Effective.",
    ),
    GlbaControl(
        id="C-04",
        domain="C",
        title="Secure system development and change control",
        high_risk=False,
        citation="App B III.C.1.d",
        csf="CSF PR.PS",
        nist="800-53: SA-3, CM-3",
        frequency="Quarterly",
        objective="Security is built into the modification of information systems.",
        procedure="Inspect SDLC and change procedures; sample change tickets for evidence of security review.",
        methods=["Inspection"],
        evidence=["Change tickets", "SDLC policy"],
        scoring="Inspection required to rate Effective. Inquiry alone is insufficient.",
    ),
    GlbaControl(
        id="C-05",
        domain="C",
        title="Dual control and segregation of duties",
        high_risk=False,
        citation="App B III.C.1.e",
        csf="CSF PR.AA",
        nist="800-53: AC-5",
        frequency="Semi-Annual",
        objective="Procedures prevent unilateral execution of high-risk actions.",
        procedure="Inspect segregation-of-duties matrix; reperform on a sample sensitive function.",
        methods=["Inspection", "Reperformance"],
        evidence=["SoD matrix", "Role mappings"],
        scoring="Inspection required to rate Effective. Inquiry alone is insufficient.",
    ),
    GlbaControl(
        id="C-06",
        domain="C",
        title="Monitoring and intrusion detection",
        high_risk=True,
        citation="App B III.C.1.f",
        csf="CSF DE.CM",
        nist="800-53: SI-4, AU-6",
        frequency="Continuous",
        objective="Systems are monitored to detect actual and attempted attacks or intrusions.",
        procedure="Inspect monitoring/SIEM coverage; observe alert handling on a sample of alerts.",
        methods=["Inspection", "Observation", "Reperformance"],
        evidence=["SIEM configuration", "Alert tickets"],
        scoring="high-risk control — Inspection + Reperformance required to rate Effective.",
    ),
    GlbaControl(
        id="C-07",
        domain="C",
        title="Incident response program",
        high_risk=True,
        citation="App B III.C.1.g",
        csf="CSF RS.MA",
        nist="800-53: IR-4, IR-8",
        frequency="Annual",
        objective="Response measures exist for unauthorized access to or use of customer information.",
        procedure="Inspect IR plan; verify exercise evidence; sample a real incident for proper handling.",
        methods=["Inspection", "Reperformance"],
        evidence=["IR plan", "Exercise records", "Incident log"],
        scoring="high-risk control — Inspection + Reperformance required to rate Effective.",
    ),
    GlbaControl(
        id="C-08",
        domain="C",
        title="Environmental and physical protection",
        high_risk=False,
        citation="App B III.C.1.h",
        csf="CSF PR.IR",
        nist="800-53: PE-13, PE-14, PE-15",
        frequency="Annual",
        objective="Customer information is protected against physical destruction or damage.",
        procedure="Observe environmental controls (fire suppression, power, climate).",
        methods=["Observation", "Inspection"],
        evidence=["Facility environmental assessment"],
        scoring="Inspection required to rate Effective. Inquiry alone is insufficient.",
    ),
    GlbaControl(
        id="C-09",
        domain="C",
        title="Staff training and awareness",
        high_risk=False,
        citation="App B III.C.2",
        csf="CSF PR.AT",
        nist="800-53: AT-2, AT-3",
        frequency="Annual",
        objective="Staff are trained to implement the ISP.",
        procedure="Inspect training records; verify completion rates against population.",
        methods=["Inspection"],
        evidence=["LMS records", "Training curriculum"],
        scoring="Inspection required to rate Effective. Inquiry alone is insufficient.",
    ),
    GlbaControl(
        id="C-10",
        domain="C",
        title="Testing of key controls",
        high_risk=True,
        citation="App B III.C.3",
        csf="CSF DE.CM",
        nist="800-53: CA-2, CA-7, RA-5",
        frequency="Annual",
        objective="Key controls, systems, and procedures are regularly tested by independent or qualified parties.",
        procedure="Inspect test plan and most recent results (penetration test, vulnerability scans, control tests); confirm independence of testers.",
        methods=["Inspection", "Reperformance"],
        evidence=["Penetration test report", "Vulnerability scan results", "Test schedule"],
        scoring="high-risk control — Inspection + Reperformance required to rate Effective.",
    ),
    GlbaControl(
        id="D-01",
        domain="D",
        title="Due diligence in provider selection",
        high_risk=False,
        citation="App B III.D.1",
        csf="CSF GV.SC",
        nist="800-53: SR-3, SA-9",
        frequency="Event-Driven",
        objective="Service providers are selected based on their capability to safeguard customer information.",
        procedure="Inspect due-diligence records on a sample of vendors.",
        methods=["Inspection"],
        evidence=["Vendor due-diligence files"],
        scoring="Inspection required to rate Effective. Inquiry alone is insufficient.",
    ),
    GlbaControl(
        id="D-02",
        domain="D",
        title="Contractual safeguard requirements",
        high_risk=False,
        citation="App B III.D.2",
        csf="CSF GV.SC",
        nist="800-53: SR-2, SA-9",
        frequency="Annual",
        objective="Contracts require providers to implement appropriate safeguards.",
        procedure="Inspect a sample of contracts for required security clauses.",
        methods=["Inspection"],
        evidence=["Contract clauses"],
        scoring="Inspection required to rate Effective. Inquiry alone is insufficient.",
    ),
    GlbaControl(
        id="D-03",
        domain="D",
        title="Monitoring of providers",
        high_risk=False,
        citation="App B III.D.3",
        csf="CSF GV.SC",
        nist="800-53: SR-6",
        frequency="Annual",
        objective="Provider performance is monitored where indicated by the bank's risk assessment.",
        procedure="Inspect SOC reports and monitoring evidence on a sample of providers.",
        methods=["Inspection"],
        evidence=["SOC 2 reports", "Monitoring logs"],
        scoring="Inspection required to rate Effective. Inquiry alone is insufficient.",
    ),
    GlbaControl(
        id="E-01",
        domain="E",
        title="Program monitoring and adjustment",
        high_risk=False,
        citation="App B III.E",
        csf="CSF ID.IM",
        nist="800-53: CA-7, PL-2",
        frequency="Annual",
        objective="The ISP is adjusted in light of changes in technology, threats, and business arrangements.",
        procedure="Inspect evidence of periodic review and update; trace a change triggered by a new threat or business change.",
        methods=["Inspection"],
        evidence=["Review log", "Updated ISP versions"],
        scoring="Inspection required to rate Effective. Inquiry alone is insufficient.",
    ),
    GlbaControl(
        id="E-02",
        domain="E",
        title="Business continuity and resilience",
        high_risk=False,
        citation="App B III.C.1.h",
        csf="CSF PR.IR / RC.RP",
        nist="800-53: CP-2, CP-9, CP-10",
        frequency="Annual",
        objective="Continuity arrangements protect the availability of customer information.",
        procedure="Inspect BCP/DR plan and most recent test results.",
        methods=["Inspection", "Reperformance"],
        evidence=["BCP/DR plan", "DR test reports"],
        scoring="Inspection required to rate Effective. Inquiry alone is insufficient.",
    ),
    GlbaControl(
        id="F-01",
        domain="F",
        title="Initial and annual privacy notices",
        high_risk=False,
        citation="12 CFR 1016.4-.5",
        csf="CSF GV.PO",
        nist="800-53: —",
        frequency="Annual",
        objective="Privacy notices are provided as required, including annual-notice exception eligibility.",
        procedure="Inspect notice content and delivery records; verify eligibility for the annual-notice exception if claimed.",
        methods=["Inspection"],
        evidence=["Privacy notice", "Delivery logs"],
        scoring="Inspection required to rate Effective. Inquiry alone is insufficient.",
    ),
    GlbaControl(
        id="F-02",
        domain="F",
        title="Opt-out rights and mechanism",
        high_risk=False,
        citation="12 CFR 1016.7-.10",
        csf="CSF GV.PO",
        nist="800-53: —",
        frequency="Annual",
        objective="Customers can opt out of covered information-sharing.",
        procedure="Inspect opt-out process; reperform a sample opt-out request end to end.",
        methods=["Inspection", "Reperformance"],
        evidence=["Opt-out records", "Process documentation"],
        scoring="Inspection required to rate Effective. Inquiry alone is insufficient.",
    ),
    GlbaControl(
        id="F-03",
        domain="F",
        title="Limits on sharing with nonaffiliated third parties",
        high_risk=False,
        citation="12 CFR 1016.10-.13",
        csf="CSF GV.SC",
        nist="800-53: —",
        frequency="Annual",
        objective="Information sharing complies with disclosure limits and stated notices.",
        procedure="Inspect data-sharing inventory against the privacy notice; sample disclosures.",
        methods=["Inspection"],
        evidence=["Sharing inventory", "Sharing agreements"],
        scoring="Inspection required to rate Effective. Inquiry alone is insufficient.",
    ),
    GlbaControl(
        id="F-04",
        domain="F",
        title="Pretext and unauthorized-access safeguards",
        high_risk=False,
        citation="GLBA Section 521",
        csf="CSF PR.AA",
        nist="800-53: IA-2, AT-2",
        frequency="Annual",
        objective="Controls deter social-engineering access to customer information.",
        procedure="Inspect authentication and caller-verification procedures; review related training.",
        methods=["Inspection"],
        evidence=["Caller-verification procedure", "Training records"],
        scoring="Inspection required to rate Effective. Inquiry alone is insufficient.",
    ),
]


# Lookup by control id for the report renderer.
GLBA_CONTROLS_BY_ID = {c.id: c for c in GLBA_CONTROLS}
